apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sms_spam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Sms_spamanalysis
  template:
    metadata:
      labels:
        app: Sms_spamanalysis
    spec:
      containers:
      - name: nlp-app
        image: gcr.io/k8s-sent-deployment/myapp:v1
        ports:
        - containerPort: 5000